version: '3'
services:
  atcoder:
    restart: always
    build:
      dockerfile: ./Dockerfile
    image: atcoder
    container_name: atcoder
    working_dir: '/root/app'
    tty: true
    volumes:
      - ./app:/root/app